### ISSUE TITLE
Could not retrieve the reqpayload error 

### ISSUE THREAD

**Issue by RedManMark86** [eracknaphobia/plugin.video.psvue#3]
I'm getting a
"could not retrieve the reqpayload" error

when trying to login.

Looking at the Kodi log it is saying this.

C:\Users\markg\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

I'm on windows so the link it gives isn't of much use.

**Comment by eracknaphobia** [comment]
That is a warning about python requests verify being set to false. Not an error and most likely not the cause of your issue.

Hmm, actually verify should be set to True in the latest version. Can you open `C:\Users\markg\AppData\Roaming\Kodi\addons\plugin.video.psvue\ps_vue.py` the very last line in that file should say `VERIFY = True`, if so try switching it to `False` and test.

**Comment by snoopyjoe** [comment]
The reqPayload error is due to a location error with your Sony account. For some reason, especially if you logged into PS Vue on a mobile device, Sony is changing your home zip code and IP. Only solution is to call or chat with PS Vue customer service and tell them you're getting error code 3000 home location error on your Android TV. They should reset your zip code and IP so the next time you login will be as if it's the first time you're logging in. Just make sure the first time you login is from your Kodi device and you are not behind a VPN or dynamic IP.
